# Generated by Django 5.2.5 on 2025-08-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_icoon_planet_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='icon',
            field=models.CharField(max_length=7),
        ),
    ]
