# Generated by Django 5.2.5 on 2025-08-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_planet_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='icon',
            new_name='icon1',
        ),
        migrations.AddField(
            model_name='planet',
            name='icon2',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
