# Generated by Django 5.2.5 on 2025-08-19 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_group_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='stars',
            name='Group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='starss', to='apps.group'),
            preserve_default=False,
        ),
    ]
