# Generated by Django 5.2.5 on 2025-08-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_star_delete_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='title2',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='title2',
            new_name='title',
        ),
    ]
