# Generated by Django 5.2.5 on 2025-08-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_about_galaxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='About_galaxy',
        ),
    ]
