# Generated by Django 5.2.5 on 2025-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_exploration_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holes_Matter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
