# Generated by Django 5.2.5 on 2025-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_holes_matter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest', models.CharField(choices=[('planets', 'Planets & Solar System'), ('galaxies', 'Galaxies & Stars'), ('black-holes', 'Black Holes & Physics'), ('exploration', 'Space Exploration'), ('all', 'All Topics')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
